### ISSUE TITLE
[IMPORTANT] Project moved

### ISSUE THREAD

**Issue by georg-jung** [Technion236272/2020b-Haifa3D#29]
This project moved to the new [Haifa3D GitHub org](https://github.com/Haifa3D): <https://github.com/Haifa3D/haifa3d-hand-app>. Please use the issues there, watch that repo, etc. @mikimn, I invited you to be an admin of the org too.

It'd be great if an admin of this repo (@Saharco @mikimn) could make the [`moved-notice`](https://github.com/Technion236503/2020b-Haifa3D/tree/moved-notice) branch the default branch on this repo to provide a nice but non-breaking redirection for visitors of this repo.

**Comment by Saharco** [comment]
done, thanks 👍

**Comment by georg-jung** [comment]
Thanks for the immediate action ;-)
